version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          command: |
            pip install awsebcli --upgrade
            mv ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/Dockerfile ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/Dockerfile.local
            zip ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/go-sample.zip ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/*

      # deploy to erasticbeanstalk
      - deploy:
          command: cd ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/ && eb deploy
