version: 2
jobs:
  archive:
    machine: true
    working_directory: ~/project/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run:
          name: Archive
          command: |
            mv ./eb-go-sample/Dockerfile ./eb-go-sample/Dockerfile.local
            zip ./eb-go-sample/go-sample.zip ./eb-go-sample/*

      -  persist_to_workspace:
          root: . # working_directoryからの相対パス
          paths:
            - .   # rootからの相対パス
  deploy:
    machine: true
    working_directory: ~/project/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - attach_workspace: # working_directoryからの相対パス
          at: .
      - run:
          name: Deploy to EB
          command: |
            pip install awsebcli --upgrade
            cd ~/project/{{ORG_NAME}}/{{REPO_NAME}}/eb-go-sample/ && eb deploy

workflows:
  version: 2
  archive_and_deploy:
    jobs:
      - archive
      - deploy:
          requires:
            - archive
