branch-defaults:
  default:
    environment: eb-go-Sample2-env
environment-defaults:
  eb-go-Sample2-env:
    branch: null
    repository: null
global:
  application_name: eb-go-sample2
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/Preconfigured
    Docker - Go 1.4 running on 64bit Debian/2.12.9
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  profile: eb-cli
  workspace_type: Application
